export const dashboardData = {
  initialSavedJobs: {
    cedar: false,
    sunny: true,
    harbour: false,
  },
  savedJobsBeforeRecommendations: 5,
  profileSetupItems: [
    { title: 'Add an intro video', description: '30–60 seconds' },
    { title: 'Upload your résumé', description: 'PDF or Word' },
    { title: 'Teaching philosophy', description: 'A few sentences' },
  ],
  stats: [
    {
      id: 'active-applications',
      label: 'Active applications',
      value: '4',
      note: '1 new this week',
      color: '#17121f',
    },
    {
      id: 'interviews',
      label: 'Interviews',
      value: '1',
      note: 'Thu, Oct 8',
      color: '#42007b',
    },
    {
      id: 'saved-jobs',
      label: 'Saved jobs',
      value: '6',
      note: '2 closing soon',
      color: '#17121f',
    },
    {
      id: 'profile-views',
      label: 'Profile views',
      value: '23',
      note: 'last 30 days',
      color: '#016516',
    },
  ],
  applications: [
    {
      initials: 'LS',
      avatarBackground: '#fff6d6',
      avatarColor: '#7a5a00',
      title: 'Early Childhood Educator',
      centre: 'Little Sprouts Daycare',
      date: 'Sep 22',
      status: 'Interview',
      step: 4,
    },
    {
      initials: 'MG',
      avatarBackground: '#e8f3ea',
      avatarColor: '#016516',
      title: 'Infant / Toddler Educator',
      centre: 'Maple Grove Montessori',
      date: 'Sep 24',
      status: 'Shortlisted',
      step: 3,
    },
    {
      initials: 'HH',
      avatarBackground: '#fdebe4',
      avatarColor: '#8a3414',
      title: 'Substitute ECE (On-call)',
      centre: 'Happy Hearts Early Learning',
      date: 'Sep 26',
      status: 'Reviewed',
      step: 2,
    },
    {
      initials: 'BB',
      avatarBackground: '#e6eef8',
      avatarColor: '#24466e',
      title: 'ECE — Preschool room',
      centre: 'Bright Beginnings Childcare',
      date: 'Sep 29',
      status: 'New',
      step: 1,
    },
  ],
  recommendedJobs: [
    {
      id: 'cedar',
      initials: 'CS',
      avatarBackground: '#e8f3ea',
      avatarColor: '#016516',
      title: 'Centre Supervisor',
      centre: 'Cedar & Moss',
      distance: '4.8 km',
      schedule: 'Full-time',
      detail: 'Leadership',
    },
    {
      id: 'sunny',
      initials: 'SP',
      avatarBackground: '#f4effa',
      avatarColor: '#42007b',
      title: 'Early Childhood Educator',
      centre: 'Sunny Park Childcare',
      distance: '6.1 km',
      schedule: 'Full-time',
      detail: 'Salary listed',
    },
    {
      id: 'harbour',
      initials: 'KH',
      avatarBackground: '#fff6d6',
      avatarColor: '#7a5a00',
      title: 'Infant / Toddler Educator',
      centre: 'Kids’ Harbour',
      distance: '9.3 km',
      schedule: 'Part-time',
      detail: 'Mornings',
    },
  ],
  activity: [
    {
      message: 'Little Sprouts moved you to Interview',
      when: '2 hours ago',
      color: '#42007b',
    },
    {
      message: 'Maple Grove Montessori viewed your profile',
      when: 'Yesterday',
      color: '#016516',
    },
    {
      message: 'Happy Hearts reviewed your application',
      when: 'Sep 28',
      color: '#e6b300',
    },
    {
      message: 'You applied to Bright Beginnings',
      when: 'Sep 29',
      color: '#cfc6d6',
    },
  ],
  quickLinks: [
    'Update employment preferences',
    'Upload a new résumé',
    'Notification settings',
    'Educator resources',
  ],
};

export const practicumPlacementCount = 2;
