export const searchTabs = {
  care: {
    label: 'Childcare',
    fields: [
      ['Location', 'City or postal code'],
      ["Child's age", 'Infant, toddler, preschool…'],
      ['Program', 'Any program'],
    ],
    chips: ['Infant care', 'Spaces available now', 'Before & after school', 'Accepting waitlist'],
    note: 'No account needed — contact centres, book tours and join waitlists directly.',
    button: 'Find childcare',
  },
  jobs: {
    label: 'Jobs',
    fields: [
      ['Role', 'Job title or keyword'],
      ['Location', 'City or postal code'],
      ['Type', 'Full-time, practicum…'],
    ],
    chips: ['Full-time ECE', 'Practicum placements', 'Substitute / on-call', 'Infant / toddler'],
    note: 'ECE student? Switch on practicum mode after you sign up.',
    button: 'Search jobs',
  },
  pros: {
    label: 'Professionals',
    fields: [
      ['Service', 'Speech therapy, licensing, design…'],
      ['Location', 'City or service area'],
    ],
    chips: ['Licensing consultants', 'Speech-language pathologists', 'Bookkeepers', 'Playground designers'],
    note: 'Only verified or claimed listings show a badge.',
    button: 'Find services',
  },
};

export const audiences = [
  {
    eyebrow: 'For parents',
    title: 'Find childcare you feel good about.',
    points: [
      'Search by location, age and program',
      'Watch welcome videos, see availability',
      'Book tours or join waitlists — no account',
    ],
    action: 'Search childcare',
    href: '/childcare-search',
    link: 'Guides',
    linkHref: '#footer',
    tone: 'lavender',
  },
  {
    eyebrow: 'For educators',
    title: 'Get hired for who you are.',
    points: [
      'Jobs and practicums within your radius',
      'A profile with intro video and philosophy',
      'Apply in minutes, track every status',
    ],
    action: 'Browse jobs',
    href: '#jobs',
    link: 'Profile',
    linkHref: '#signup',
    tone: 'green',
  },
  {
    eyebrow: 'For childcare centres',
    title: 'Hire, showcase and grow.',
    points: [
      'Post jobs and manage applicants',
      'A public profile families trust',
      'Find reliable services in the directory',
    ],
    action: 'Post a job',
    href: '#signup',
    link: 'Profile',
    linkHref: '#signup',
    tone: 'ink',
  },
];

export const jobFilters = [
  ['all', 'All roles'],
  ['ft', 'Full-time'],
  ['pt', 'Part-time'],
  ['cs', 'Casual'],
  ['sb', 'Substitute'],
  ['pr', 'Practicum'],
];

export const jobs = [
  {
    typeKey: 'ft',
    initials: 'LS',
    title: 'Early Childhood Educator',
    centre: 'Little Sprouts Daycare',
    city: 'Burnaby',
    distance: '2.4 km',
    type: 'Full-time',
    extra: '2 positions',
    posted: '2 days ago',
    tone: 'purple',
  },
  {
    typeKey: 'pt',
    initials: 'MG',
    title: 'Infant / Toddler Educator',
    centre: 'Maple Grove Montessori',
    city: 'Vancouver',
    distance: '7.2 km',
    type: 'Part-time',
    extra: 'Mornings',
    posted: '3 days ago',
    tone: 'purple',
  },
  {
    typeKey: 'pr',
    initials: 'CM',
    title: 'ECE Practicum — Level 2',
    centre: 'Cedar & Moss Nature School',
    city: 'North Vancouver',
    distance: '4.8 km',
    type: 'Practicum',
    extra: 'January intake',
    posted: '4 days ago',
    tone: 'gold',
  },
  {
    typeKey: 'sb',
    initials: 'HH',
    title: 'Substitute ECE (On-call)',
    centre: 'Happy Hearts Early Learning',
    city: 'Richmond',
    distance: '9.1 km',
    type: 'Substitute',
    extra: 'Flexible days',
    posted: '5 days ago',
    tone: 'green',
  },
  {
    typeKey: 'ft',
    initials: 'LS',
    title: 'Centre Supervisor',
    centre: 'Little Sprouts Daycare',
    city: 'Burnaby',
    distance: '2.4 km',
    type: 'Full-time',
    extra: 'Leadership',
    posted: '1 week ago',
    tone: 'purple',
  },
  {
    typeKey: 'cs',
    initials: 'BB',
    title: 'Casual ECE Assistant',
    centre: 'Bright Beginnings Childcare',
    city: 'Surrey',
    distance: '18 km',
    type: 'Casual',
    extra: 'Weekdays',
    posted: '1 week ago',
    tone: 'green',
  },
];

export const centres = [
  {
    name: 'Cedar & Moss Nature School',
    label: 'Verified · Outdoor program',
    ages: '2.5–5 yrs',
    distance: '4.8 km',
    video: '1:12',
    availability: 'Spaces available',
    availabilityColor: '#016516',
    tone: 'green',
    cover: '#EAF3EB',
    orb: '#D3E8D5',
    sun: '#FFE9A8',
  },
  {
    name: 'Little Sprouts Daycare',
    label: 'Verified · Licensed group care',
    ages: '6 mo–5 yrs',
    distance: '2.4 km',
    video: '0:58',
    availability: 'Waitlist open',
    availabilityColor: '#7A5A00',
    tone: 'gold',
    cover: '#FFF3D1',
    orb: '#FBE3A4',
    sun: '#F7C9B8',
  },
  {
    name: 'Happy Hearts Early Learning',
    label: 'Verified · Preschool',
    ages: '3–5 yrs',
    distance: '3.1 km',
    video: '1:30',
    availability: 'Tours this week',
    availabilityColor: '#42007B',
    tone: 'lavender',
    cover: '#F1E9FA',
    orb: '#E0D0F2',
    sun: '#CFE6D2',
  },
];

export const professionalFilters = [
  ['all', 'All services'],
  ['therapy', 'Therapy & development'],
  ['biz', 'Licensing & business'],
  ['learn', 'Training & curriculum'],
  ['space', 'Spaces & design'],
];

export const professionals = [
  {
    group: 'therapy',
    initials: 'MC',
    name: 'Maya Chen, SLP',
    category: 'Speech-Language Pathologist',
    area: 'Metro Vancouver',
    description: 'Early language screening and in-centre visits for 2–5 year olds.',
    status: 'Verified',
    cta: 'Contact',
    tone: 'lavender',
  },
  {
    group: 'biz',
    initials: 'BL',
    name: 'Brightpath Licensing',
    category: 'Licensing Consultant',
    area: 'BC-wide',
    description: 'New centre setup, inspection prep and policy reviews.',
    status: 'Verified',
    featured: true,
    cta: 'Contact',
    tone: 'green',
  },
  {
    group: 'biz',
    initials: 'LL',
    name: 'Little Ledger Bookkeeping',
    category: 'Bookkeeper',
    area: 'Lower Mainland',
    description: 'Listed by Educator Connect from public business information.',
    status: 'Unclaimed listing',
    cta: 'Claim profile',
    tone: 'neutral',
  },
  {
    group: 'space',
    initials: 'NP',
    name: 'Northshore Play Design',
    category: 'Playground Designer',
    area: 'British Columbia',
    description: 'Natural playscapes and outdoor learning environments.',
    status: 'Claimed',
    cta: 'Book a consultation',
    tone: 'gold',
  },
  {
    group: 'therapy',
    initials: 'HO',
    name: 'Harbour OT for Kids',
    category: 'Occupational Therapist',
    area: 'Vancouver & North Shore',
    description: 'Sensory and fine-motor support, staff workshops.',
    status: 'Claimed',
    cta: 'Book a consultation',
    tone: 'blue',
  },
  {
    group: 'learn',
    initials: 'RL',
    name: 'Rooted Learning Workshops',
    category: 'Trainer & Workshop Facilitator',
    area: 'Online · BC',
    description: 'Listed by Educator Connect from public business information.',
    status: 'Unclaimed listing',
    cta: 'Claim profile',
    tone: 'neutral',
  },
  {
    group: 'learn',
    initials: 'EC',
    name: 'Emergent Curriculum Co.',
    category: 'Curriculum Specialist',
    area: 'Vancouver Island',
    description: 'Play-based curriculum planning and documentation coaching.',
    status: 'Verified',
    cta: 'Contact',
    tone: 'green',
  },
  {
    group: 'space',
    initials: 'SI',
    name: 'Small Spaces Interiors',
    category: 'Interior Designer',
    area: 'Lower Mainland',
    description: 'Calm, child-height classroom layouts and furnishing plans.',
    status: 'Claimed',
    cta: 'Book a consultation',
    tone: 'peach',
  },
];

export const trustItems = [
  {
    title: 'Verified centres',
    description: 'Licensing shown only once validated.',
    tone: 'green',
  },
  {
    title: 'Verified educators',
    description: 'Certifications checked where applicable.',
    tone: 'lavender',
  },
  {
    title: 'Claimed pros',
    description: 'Ownership confirmed before editing.',
    tone: 'gold',
  },
  {
    title: 'Privacy first',
    description: 'Only the child info centres need.',
    tone: 'blue',
  },
];

export const footerColumns = [
  { title: 'Find childcare', links: ['Search centres', 'Parent resources', 'Tours & waitlists'] },
  { title: 'Jobs', links: ['Browse jobs', 'For educators', 'For ECE students'] },
  { title: 'For centres', links: ['Create centre profile', 'Post a job', 'Find educators', 'Practicum opportunities'] },
  { title: 'Directory', links: ['Search professionals', 'Browse categories', 'Add your profile', 'Claim your profile'] },
  { title: 'Company', links: ['About', 'Resources', 'Help Centre', 'Contact'] },
];

export const mobileFooterColumns = [
  { title: 'Find Childcare', links: ['Search centres', 'Parent resources'] },
  { title: 'Jobs', links: ['Browse jobs', 'For ECE students'] },
  { title: 'For Centres', links: ['Create profile', 'Post a job', 'Find educators'] },
  { title: 'Directory', links: ['Search professionals', 'Add your profile', 'Claim your profile'] },
];
